server:
  port: 8080

spring:
  application:
    name: idempotency-receiver
  kafka:
    bootstrap-servers: kafka:9092
    template:
      lap-time-completed: lap-time-completed
    producer:
      properties:
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      properties:
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: org.apache.kafka.common.serialization.StringSerializer
